# Generated by Django 5.2.6 on 2025-09-30 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_or_equipment",
                    models.CharField(
                        max_length=100, verbose_name="Area/Attrezzatura Pulita"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Ora"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Note Aggiuntive"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrazione Pulizia",
                "verbose_name_plural": "Registrazioni Pulizie",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(max_length=100, verbose_name="Attrezzatura"),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Temperatura (°C)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Ora"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrazione Temperatura",
                "verbose_name_plural": "Registrazioni Temperature",
                "ordering": ["-timestamp"],
            },
        ),
    ]
