# Generated by Django 5.2.6 on 2025-09-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_cleaningrecord_temperaturerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome Ingrediente"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Grammi"),
                            ("kg", "Chilogrammi"),
                            ("ml", "Millilitri"),
                            ("l", "Litri"),
                            ("pz", "Pezzi"),
                        ],
                        max_length=5,
                        verbose_name="Unità di Misura",
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantità in Magazzino",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Costo per Unità (€)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredienti",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome Ricetta")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                ("instructions", models.TextField(verbose_name="Istruzioni")),
            ],
            options={
                "verbose_name": "Ricetta",
                "verbose_name_plural": "Ricette",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Quantità Richiesta",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.ingredient",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.recipe",
                        verbose_name="Ricetta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente della Ricetta",
                "verbose_name_plural": "Ingredienti della Ricetta",
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="kitchen.RecipeIngredient",
                to="kitchen.ingredient",
                verbose_name="Ingredienti",
            ),
        ),
    ]
