# Generated by Django 5.2.6 on 2025-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_ingredient_recipe_recipeingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
    ]
