# Generated by Django 5.2.6 on 2025-10-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_ingredient_recipe_recipeingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="minimum_threshold",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Soglia Minima"
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Messaggio")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Ora"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Letta")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kitchen.ingredient",
                        verbose_name="Ingrediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifica",
                "verbose_name_plural": "Notifiche",
                "ordering": ["-timestamp"],
            },
        ),
    ]
